# Generated by Django 3.2.5 on 2022-12-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseFinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='xml_file',
            field=models.FileField(default=None, upload_to='courseFinder/media/'),
        ),
    ]
