# Generated by Django 3.2.5 on 2022-10-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a school name (e.g. Smith College)', max_length=200, verbose_name='Name')),
                ('state', models.CharField(help_text='Select a state', max_length=2, verbose_name='State')),
                ('year', models.IntegerField(help_text='Enter a year', verbose_name='Year')),
                ('pdf', models.FileField(upload_to='../tripodsWeb/media/', verbose_name='PDF')),
                ('csv', models.FileField(upload_to='../tripodsWeb/media/', verbose_name='CSV')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a school name (e.g. Smith College)', max_length=200, verbose_name='Name')),
                ('year', models.IntegerField(help_text='Enter a year', verbose_name='Year')),
                ('rq_type', models.CharField(choices=[('Pu', 'Public'), ('R', 'Research'), ('Pr', 'Private')], max_length=2)),
                ('search_terms', models.TextField()),
                ('category', models.TextField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tripodsApp.school')),
            ],
        ),
    ]
