# Generated by Django 3.2.5 on 2022-10-12 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripodsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'managed': False},
        ),
    ]
