# Generated by Django 3.2.5 on 2022-10-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripodsApp', '0002_auto_20221012_0238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Enter a year', verbose_name='Year')),
                ('pdf', models.FileField(upload_to='../tripodsWeb/media/', verbose_name='PDF')),
                ('csv', models.FileField(upload_to='../tripodsWeb/media/', verbose_name='CSV')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tripodsApp.school')),
            ],
        ),
    ]
