# Generated by Django 3.2.5 on 2022-10-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripodsApp', '0004_auto_20221017_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='xml',
            field=models.FileField(blank=True, null=True, upload_to='../tripodsWeb/media/', verbose_name='XML'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to='../tripodsWeb/media/', verbose_name='CSV'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='../tripodsWeb/media/', verbose_name='PDF'),
        ),
    ]
