# Generated by Django 3.2.5 on 2022-10-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripodsApp', '0006_catalog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='catalog',
        ),
        migrations.AddField(
            model_name='catalog',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tripodsApp.school'),
        ),
        migrations.AddField(
            model_name='request',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tripodsApp.catalog'),
        ),
        migrations.AddField(
            model_name='request',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tripodsApp.school'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='CSV'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='xml',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='XML'),
        ),
    ]
