# Generated by Django 3.2.5 on 2022-10-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripodsApp', '0007_auto_20221028_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(default='catalog', help_text='Enter a school name and year (e.g. Smith College 22-23)', max_length=200, verbose_name='Name'),
        ),
    ]
