# Generated by Django 3.2.5 on 2022-11-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripodsApp', '0009_auto_20221107_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='pdf',
            field=models.URLField(blank=True, null=True, verbose_name='PDF URL'),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='request',
            name='rq_type',
            field=models.CharField(choices=[('Pu', 'Public'), ('R', 'Research'), ('Pr', 'Private')], max_length=2, verbose_name='Request Type'),
        ),
        migrations.AlterField(
            model_name='request',
            name='search_terms',
            field=models.TextField(verbose_name='Search Terms'),
        ),
    ]
