# Generated by Django 3.2.5 on 2022-11-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripodsApp', '0010_auto_20221107_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(default='catalog', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='pdf',
            field=models.URLField(default=None, verbose_name='PDF URL'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tripodsApp.school'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='year',
            field=models.IntegerField(default=None, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='request',
            name='catalog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tripodsApp.catalog'),
        ),
        migrations.AlterField(
            model_name='request',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tripodsApp.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default=None, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default=None, max_length=2, verbose_name='State'),
        ),
    ]
