# Generated by Django 3.2.5 on 2022-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripodsApp', '0011_auto_20221107_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='pdf_file',
            field=models.FileField(default=None, upload_to='../media/'),
        ),
    ]
