# Generated by Django 3.2.5 on 2022-11-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripodsApp', '0012_catalog_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='pdf_file',
            new_name='xml_file',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='pdf',
        ),
    ]
