# Generated by Django 3.2.5 on 2022-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripodsApp', '0013_auto_20221121_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='pdf',
            field=models.URLField(default=None, verbose_name='PDF URL'),
        ),
    ]
