# Generated by Django 3.2.5 on 2022-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripodsApp', '0015_alter_catalog_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default=' {school} + {catalog}', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='pdf',
            field=models.URLField(default=None, verbose_name='PDF URL'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='xml_file',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
