#!/bin/sh
file=$1
#tag=$2
#replaces either '</b>' or '<b>' with nothing
sed -E "s~<(/|)b>~~g" $file
#sed -E "s~<(/|)${tag}>~~g" $file # way to remove a given tag?
#grep -E "^<p><b>[A-Z]{2,}(-|\ *)[0-9]{2,}"
